name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '13'
    - name: Install modules
      run: yarn
    - name: Linter
      run: yarn lint  
    - name: Lighthouse Check
      uses: foo-software/lighthouse-check-action@v2.0.2
